# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'TestViewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'

  # Pods for TestViewCode
end

target 'TestViewCodeTests' do
  pod 'Quick'
  pod 'Nimble'
  pod 'Nimble-Snapshots'
end
